#!/usr/bin/env bash
#
# llama_cpp_source_archive_for_llm_analysis.sh
#
# Script generated by ChatGPT in response to my request to filter out all of the relevent source code.
#
# Prompts:
# I would like to develop a deeper technical understanding of the llama-server execution path and the GPU
# compute path to truly understand what is happening when I issue a prompt from OpenCode via the API. Since
# llama-server is peer-reviewed and widely adopted, it serves as an excellent reference for how to implement
# computational inference successfully.
#
# Before we get further, I'd like to develop a comprehensive script to
# provide 100% of the source needed for this exercise. I'm happy to iterate on the definition of the script
# until we get it right. Would it help if I provided a list of all of the files in the repository so that you
# may construct a graph analysis of the constituent parts?
#
# It gives us:
#    the source bundle,
#    exact provenance,
#    a complete repo manifest,
#    explicit inclusion/exclusion accounting.
#
# The broader pattern here is:
#    Create a curated source bundle
#    Create metadata that describes what was included and excluded
#    Create a structural map of the code
#    Create a size map of the repository
#    Use the maps to guide deeper semantic analysis
#
# That general workflow scales well to other repos. It turns “please understand this codebase” into a repeatable pipeline:
#
# repository
# -> manifest
# -> architectural candidate list
# -> size analysis
# -> execution-path tracing
# -> synthesized understanding
#
# General method for other repositories
#
# This same process is broadly applicable.
#
# For any repo, I would use this layered method:
# Layer 1: inventory
#
# What files exist?
# Layer 2: candidate graph
#
# Which files appear central by naming, build references, and directory role?
# Layer 3: size profile
#
# Where does disk usage actually go?
# Layer 4: execution path
#
# What is the real call path?
# Layer 5: semantic synthesis
#
# What is the architecture really doing, and why was it built this way?
#
# That is the general pattern you are seeing emerge — and yes, it is a strong collaborative workflow for source comprehension.
#



#!/usr/bin/env bash
set -euo pipefail

repo="${1:-$PWD}"
out_base="${2:-llama_cpp_source_archive_for_llm_analysis}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

cd "$repo"

commit="$(git rev-parse HEAD)"
short_commit="$(printf '%s' "$commit" | cut -c1-9)"
archive_root="${out_base}_${short_commit}"
readme_file="${archive_root}_readme.txt"

meta_dir="$tmpdir/meta"
mkdir -p "$meta_dir"

printf '%s\n' "$commit" > "$meta_dir/HEAD_COMMIT.txt"
git status --short > "$meta_dir/GIT_STATUS.txt"
git remote -v > "$meta_dir/GIT_REMOTES.txt" || true
git ls-files | sort > "$meta_dir/MANIFEST_ALL.txt"

{
    printf '%s\n' 'CMakeLists.txt'
    printf '%s\n' 'CMakePresets.json'
    printf '%s\n' 'Makefile'
    git ls-files \
        src \
        src/models \
        include \
        common \
        ggml \
        tools/server \
        vendor/cpp-httplib \
        cmake \
        examples/batched \
        benches \
        '*.cmake' 2>/dev/null || true
} | sed '/^$/d' | sort -u > "$meta_dir/MANIFEST_ARCHIVED.txt"

comm -23 "$meta_dir/MANIFEST_ALL.txt" "$meta_dir/MANIFEST_ARCHIVED.txt" > "$meta_dir/MANIFEST_EXCLUDED.txt"

{
    printf 'Top-level tracked directories\n\n'
    git ls-files | awk -F/ '{print $1}' | sort | uniq -c | sort -k2
} > "$meta_dir/TREE_TOPLEVEL.txt"

{
    printf 'Tracked file counts by directory\n\n'
    git ls-files | awk '
    {
        path=$0
        n=split(path, a, "/")
        acc=a[1]
        count[acc]++
        for (i=2; i<n; i++) {
            acc=acc "/" a[i]
            count[acc]++
        }
    }
    END {
        for (k in count) print count[k], k
    }' | sort -k2
} > "$meta_dir/COUNTS_BY_DIR.txt"

{
    printf 'Tracked files by extension\n\n'
    git ls-files | awk '
    {
        ext="(no extension)"
        name=$0
        if (name ~ /\./) {
            sub(/^.*\./, "", name)
            ext=name
        }
        count[ext]++
    }
    END {
        for (k in count) print count[k], k
    }' | sort -k2
} > "$meta_dir/FILES_BY_EXTENSION.txt"

{
    printf 'Server / inference path candidates\n\n'
    git ls-files | grep -E \
        '(^|/)(server|http|chat|sampling|batch|kv|context|model|decode|infer|queue|task)[^/]*\.(c|cc|cpp|cxx|h|hpp|cu|cuh)$' \
        | sort || true
} > "$meta_dir/ENTRYPOINT_CANDIDATES.txt"

{
    printf 'Translation units (.c, .cc, .cpp, .cxx, .cu)\n\n'
    git ls-files | grep -E '\.(c|cc|cpp|cxx|cu)$' | sort || true
} > "$meta_dir/TRANSLATION_UNITS.txt"

{
    printf 'Top-level filesystem usage\n\n'
    for path in * .*; do
        [ "$path" = "." ] && continue
        [ "$path" = ".." ] && continue
        [ -e "$path" ] || continue
        du -sh "$path" 2>/dev/null || true
    done | sort -h
} > "$meta_dir/DU_TOPLEVEL.txt"

{
    printf 'Filesystem usage of archived top-level paths\n\n'
    awk -F/ '{print $1}' "$meta_dir/MANIFEST_ARCHIVED.txt" | sort -u | while IFS= read -r top; do
        [ -e "$top" ] || continue
        du -sh "$top" 2>/dev/null || true
    done | sort -h
} > "$meta_dir/DU_ARCHIVED_PATHS.txt"

{
    printf 'Largest tracked files (bytes path)\n\n'
    git ls-files | while IFS= read -r path; do
        [ -f "$path" ] || continue
        printf '%12s %s\n' "$(stat -c '%s' "$path")" "$path"
    done | sort -n
} > "$meta_dir/LARGEST_TRACKED_FILES.txt"

{
    printf 'Largest excluded tracked files (bytes path)\n\n'
    while IFS= read -r path; do
        [ -f "$path" ] || continue
        printf '%12s %s\n' "$(stat -c '%s' "$path")" "$path"
    done < "$meta_dir/MANIFEST_EXCLUDED.txt" | sort -n
} > "$meta_dir/LARGEST_EXCLUDED_TRACKED_FILES.txt"

META_DIR="$meta_dir" python3 - <<'PY' > "$meta_dir/TRACKED_SIZE_BY_TOPLEVEL.txt"
import os
import subprocess
from collections import defaultdict

files = subprocess.check_output(["git", "ls-files"], text=True).splitlines()
sizes = defaultdict(int)

for path in files:
    if not os.path.isfile(path):
        continue
    top = path.split("/", 1)[0]
    sizes[top] += os.path.getsize(path)

print("Tracked file size by top-level directory\n")
for key in sorted(sizes):
    print(f"{sizes[key]:12d} {key}")
PY

META_DIR="$meta_dir" python3 - <<'PY' > "$meta_dir/TRACKED_SIZE_ARCHIVED_VS_EXCLUDED.txt"
import os

meta_dir = os.environ["META_DIR"]

def total_size(manifest_name: str) -> int:
    total = 0
    manifest = os.path.join(meta_dir, manifest_name)
    with open(manifest, "r", encoding="utf-8") as f:
        for line in f:
            path = line.strip()
            if path and os.path.isfile(path):
                total += os.path.getsize(path)
    return total

archived = total_size("MANIFEST_ARCHIVED.txt")
excluded = total_size("MANIFEST_EXCLUDED.txt")

print("Tracked size summary\n")
print(f"archived_bytes {archived}")
print(f"excluded_bytes {excluded}")
PY

bundle_dir="$tmpdir/$archive_root"
mkdir -p "$bundle_dir/source" "$bundle_dir/meta"

tar -cf - -T "$meta_dir/MANIFEST_ARCHIVED.txt" | tar -xf - -C "$bundle_dir/source"
cp -a "$meta_dir"/. "$bundle_dir/meta"/

tar -czf "${archive_root}.tar.gz" -C "$tmpdir" "$archive_root"

{
    printf "llama.cpp inference analysis bundle\n\n"
    printf "Archive: %s.tar.gz\n" "${archive_root}"
    printf "Commit:  %s\n\n" "$commit"

    printf "Archived files: %s\n" "$(wc -l < "$meta_dir/MANIFEST_ARCHIVED.txt")"
    printf "Excluded tracked files: %s\n\n" "$(wc -l < "$meta_dir/MANIFEST_EXCLUDED.txt")"

    printf "Key directories included:\n"
    printf "  src\n"
    printf "  src/models\n"
    printf "  include\n"
    printf "  common\n"
    printf "  ggml\n"
    printf "  tools/server\n"
    printf "  vendor/cpp-httplib\n"
    printf "  cmake\n"
    printf "  examples/batched\n"
    printf "  benches\n\n"

    printf "Metadata files included:\n"
    printf "  meta/HEAD_COMMIT.txt\n"
    printf "  meta/GIT_STATUS.txt\n"
    printf "  meta/GIT_REMOTES.txt\n"
    printf "  meta/MANIFEST_ALL.txt\n"
    printf "  meta/MANIFEST_ARCHIVED.txt\n"
    printf "  meta/MANIFEST_EXCLUDED.txt\n"
    printf "  meta/TREE_TOPLEVEL.txt\n"
    printf "  meta/COUNTS_BY_DIR.txt\n"
    printf "  meta/FILES_BY_EXTENSION.txt\n"
    printf "  meta/ENTRYPOINT_CANDIDATES.txt\n"
    printf "  meta/TRANSLATION_UNITS.txt\n"
    printf "  meta/DU_TOPLEVEL.txt\n"
    printf "  meta/DU_ARCHIVED_PATHS.txt\n"
    printf "  meta/LARGEST_TRACKED_FILES.txt\n"
    printf "  meta/LARGEST_EXCLUDED_TRACKED_FILES.txt\n"
    printf "  meta/TRACKED_SIZE_BY_TOPLEVEL.txt\n"
    printf "  meta/TRACKED_SIZE_ARCHIVED_VS_EXCLUDED.txt\n"

} | tee "$readme_file"

